### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by tiagotex** [tpope/hookup#40]
I tried to use this gem to fix merge conflicts but it was not working as expected.

Merge conflicts on schema.rb were not fixed. I then noticed that the last release of this gem was in 2014 and was missing this fix to handle Rails 5 schema format https://github.com/tpope/hookup/pull/39

In the meanwhile I have resorted to installing the main branch:

```
gem install specific_install
gem specific_install -l https://github.com/tpope/hookup.git
hookup install
```

Could you release a new version of the gem that includes the current fixes in the main branch?

Thank you for the awesome gem 💚

**Comment by tpope** [comment]
Yeah okay.
