### ISSUE TITLE
Should Hookup automatically skip when rebasing? 

### ISSUE THREAD

**Issue by g-pavlik** [tpope/hookup#44]
It seems hookup's hooks run on each commit switch, but this seems detrimental for users that incorporate rebasing in their flow `git rebase origin/main` (any fail in the hook seems to crash the rebase). 

My current workaround is `SKIP_HOOKUP=1 git rebase origin/main` but I never had this issue with other similar tools like `overcommit` and `husky`. 

Is there a way to detect we're in the middle of rebase and wait util the very end?

**Comment by tpope** [comment]
It only does it mid-rebase if there's a merge conflict, right? That seems like it could be helpful.

**Comment by g-pavlik** [comment]
You're probably right, it just behaved differently than during conflict without hookup: there was a weird exception, and git would "forget" I'm in the middle of rebase (I could not do `git rebase --continue`). 
Anyway — thanks, I'll close this issue and reopen/open new when it happens again and I have more info to share.
